import { useState } from "react";
import Head from "next/head";
import AdminLayout from "~/components/Admin/AdminLayout";
import Nav from "~/components/Nav";

export default function Admin() {
  // const [drinks, setDrinks] = useState<SortedConsumption[]>(drinksList);
  // const [games, setGames] = useState<SortedConsumption[]>(gamesList);
  // const [promotions, setPromotions] =
  //   useState<SortedPromotion[]>(promotionsList);
  // const [users, setUsers] = useState<User[]>(usersList);

  return (
    <div className="">
      <Head>
        <title>JOBS | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav route="admin" />

      <main className="min-h-screen bg-gray-200">
        <AdminLayout route="admin">
          <section className="">
            <article>
              <h5>Bebida más bebida</h5>
              {/* <Table trTitles={trDrinkTitle}>
                  {drinks?.map((drink) => (
                    <RankingRow
                      key={drink.id}
                      name={drink.name}
                      total={drink.total}
                    />
                  ))}
                </Table> */}
            </article>

            <article>
              <h5>Juego más jugado</h5>
              {/* <Table trTitles={trGameTitle}>
                  {games?.map((game) => (
                    <RankingRow
                      key={game.id}
                      name={game.name}
                      total={game.total}
                    />
                  ))}
                </Table> */}
            </article>

            <article>
              <h5>Promo más canjeada</h5>
              {/* <Table trTitles={trPromotionTitle}>
                  {promotions?.map((promotion) => (
                    <RankingRow
                      key={promotion.id}
                      name={promotion.name}
                      total={promotion.total}
                    />
                  ))}
                </Table> */}
            </article>

            <article>
              <h5>Jugadores con más puntos canjeados</h5>
              {/* <Table trTitles={trPromotionTitle}>
                  {users?.map((user) => (
                    <RankingRow
                      key={user.id}
                      name={user.fullName}
                      total={user.totalPointsSpent}
                    />
                  ))}
                </Table> */}
            </article>
          </section>
        </AdminLayout>
      </main>
    </div>
  );
}
